// src/config/client.ts
export const CLIENT = {
  name: "ALEXANDRA REZENDE - PROPLÁSTICA",
  logo: "https://f58ee20228d9ca2cf6ae548dbcf2204b.r2.cloudflarestorage.com/creative-post-storage/projects/prj_293396a0-b2d8-4c69-8a80-b925666cb804/assets/1777383995587-logo_white.png?X-Amz-Expires=3600&X-Amz-Date=20260428T134914Z&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=b934f0556c87eb9d9e2b56da7aeeed98%2F20260428%2Fauto%2Fs3%2Faws4_request&X-Amz-SignedHeaders=host&X-Amz-Signature=75c7bf8b1e2c97511c53c5026235fe50af631825226d39e5e5ad218d3e9ef90a",
  favicon: "/images/favicon.png",
  siteUrl: "https://lp-alexandra-rezende-proplastica.pages.dev",
  seo: {
    title: "ALEXANDRA REZENDE - Transplante Capilar Belo Horizonte",
    description: "Recupere sua autoestima com transplante capilar fio a fio na ProPlástica em Belo Horizonte, MG. Resultados naturais e duradouros com a Dra. Alexandra Rezende e Dr. Alexandre Marcondes.",
  },
  og: { image: "/images/og.jpg" },
  schema: {
    type: "Physician",
    streetAddress: "",
    addressLocality: "Belo Horizonte",
    addressRegion: "MG",
    postalCode: "",
    sameAs: [] as string[],
  },
  fontsUrl: "https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap",
  fonts: {
    display: "Inter",
    body: "Inter",
  },
  gtmId: "GTM-XXXXXXX",
  webhookUrl: "https://webhooks02.manager01.growdoc.com.br/webhook/redirect-global",
  captureUrl: "https://lswmkiyqznvuedbuyrkt.supabase.co/functions/v1/capture-lead",
  location: "Belo Horizonte · MG",
  hero: {
    eyebrow: "Transplante Capilar · Belo Horizonte, MG",
    headingLines: ["Recupere sua autoestima com transplante capilar","fio a fio na ProPlástica"],
    credentials: ["Dra. Alexandra Rezende e Dr. Alexandre Marcondes"],
    formTitle: "Agende sua Consulta",
    ctaText: "Agendar consulta",
  },
  desires: {
    eyebrow: "Você se identifica com esses sinais?",
    heading: "Sua calvície está avançando?",
    items: [{"num":"01","text":"As entradas estão cada vez mais fundas e difíceis de disfarçar."},{"num":"02","text":"O topo da cabeça (coroa) já aparece sob a luz forte ou fotos."},{"num":"03","text":"Você evita certos cortes de cabelo ou usa boné para esconder a falha."},{"num":"04","text":"Tratamentos paliativos e loções já não fazem mais efeito."}],
    ctaSubtext: "Não espere o último fio cair. Entenda se você ainda possui área doadora para reverter a calvície com resultados naturais e sem cicatrizes lineares.",
  },
  services: {
    eyebrow: "Como Funciona o Transplante Capilar FUE?",
    heading: "No Hospital Dia, você tem acesso a um transplante capilar ",
    headingEm: "seguro,",
    items: [{"num":"01","title":"TÉCNICA F.U.E","description":"Sem cortes, sem cicatriz linear e com resultados naturais e permanentes."},{"num":"02","title":"ALTA PERFORMANCE","description":"Procedimento minimamente invasivo, feito fio a fio, para resultados naturais e recuperação rápida."},{"num":"03","title":"IMPLANTE FIOS PRÓPRIOS","description":"Seus próprios fios são implantados onde a calvície venceu, respeitando angulação e densidade natural."},{"num":"04","title":"ANESTESIA LOCAL E SEDAÇÃO","description":"Realizado com anestesia local e sedação intravenosa para seu conforto e bem-estar durante o procedimento."}],
  },
  testimonials: [{"title":"“MINHA EXPERIÊNCIA FOI ÓTIMA!”","body":"Fiz minha cirurgia e correu tudo muito bem! Atendimento atencioso, equipe cuidadosa e um ambiente que transmite segurança. Espero voltar em breve para mais um procedimento. Obrigada Dr. Leonardo e equipe ProPlástica!","author":"Patrícia Melo"},{"title":"“ATENDIMENTO QUE SUPERA EXPECTATIVAS!”","body":"Fiquei impressionado com o cuidado em relação ao paciente. Todas as etapas do processo foram explicadas com clareza, tudo muito bem organizado. Toda a equipe está de parabéns!","author":"Otávio Boaventura"},{"title":"“CIRURGIA IMPECÁVEL E CUIDADO EM CADA DETALHE!”","body":"Dr. Alexandre e equipe são super profissionais e atenciosos! Ele é experiente, criterioso e competente. A cirurgia foi um sucesso e o pós-operatório teve um cuidado impecável. As enfermeiras, secretárias e até a equipe da limpeza são incríveis! Recomendo a ProPlástica com toda confiança!","author":"Mariana Cardieri"},{"title":"“FUI PACIENTE E TAMBÉM COLABORADORA, RECOMENDO DE OLHOS FECHADOS!”","body":"Posso afirmar com certeza: o bom atendimento, a segurança e a qualidade da ProPlástica estão em primeiro lugar. Além de ter feito parte da equipe, também fui paciente e realizei 3 procedimentos com o Dr. Alexandre — todos com excelentes resultados. Parabéns à clínica e a toda equipe!","author":"Rosangela Vieira"}],
  process: {
    eyebrow: "Como Funciona",
    heading: "Do primeiro contato ao",
    headingEm: "resultado",
    steps: [
      { num: "01", title: "AGENDAMENTO", description: "Entre em contato e agende sua consulta." },
      { num: "02", title: "CONSULTA", description: "Avaliação detalhada e planejamento do tratamento." },
      { num: "03", title: "PROCEDIMENTO", description: "Realização com técnica e segurança." },
      { num: "04", title: "RESULTADO", description: "Acompanhamento e resultado esperado." },
    ],
  },
  beforeAfter: {
    eyebrow: "Resultados Reais",
    heading: "Transformações que",
    headingEm: "falam por si",
    disclaimer: "Resultados podem variar. Imagens de pacientes que autorizaram o uso.",
    items: [] as { label: string; beforeSrc: string; afterSrc: string }[],
  },
  faq: {
    eyebrow: "Dúvidas Frequentes",
    heading: "Perguntas que os pacientes mais fazem",
    items: [] as { question: string; answer: string }[],
  },
  mapSection: {
    eyebrow: "Localização",
    heading: "Venha nos conhecer",
    address: "",
    complement: "",
    schedule: "",
    phone: "",
    mapsUrl: "https://maps.google.com",
    mapsEmbed: "https://www.google.com/maps/embed?pb=",
  },
  locationSection: {
    eyebrow: "Nossa Estrutura",
    heading: "Conheça o ALEXANDRA REZENDE - PROPLÁSTICA",
    locations: [{ city: "Belo Horizonte, MG", name: "ALEXANDRA REZENDE - PROPLÁSTICA", address: "", description: "" }],
    stats: [] as { value: string; label: string }[],
  },
  gallery: {
    eyebrow: "Estrutura",
    heading: "Conheça o ALEXANDRA REZENDE - PROPLÁSTICA",
    description: "",
    images: [] as { src: string; alt: string }[],
  },
  doctors: [
    {
      crm: "",
      name: "Alexandra Rezende",
      specialty: "Transplante Capilar",
      bio: ["A Dra. Alexandra Rezende e o Dr. Alexandre Marcondes são renomados especialistas em transplante capilar, dedicados a ajudar pacientes a recuperar a autoestima através de procedimentos modernos e seguros. Na ProPlástica, utilizamos a técnica FUE para garantir resultados naturais e permanentes, sem cicatrizes lineares. Nossa equipe está comprometida com o conforto e bem-estar de cada paciente, desde a consulta inicial até a recuperação."],
      credentials: ["Dra. Alexandra Rezende e Dr. Alexandre Marcondes"],
      photo: "/images/doctor.webp",
    },
  ],
  linksUteis: { items: [] as { label: string; href: string }[] },
  footer: {
    year: new Date().getFullYear(),
    copyright: "Dr. Alexandre Marcondes Rezende · Todos os direitos reservados",
  },
} as const